buildscript {
    repositories {
        google()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {url "https://maven.google.com"}
        maven { url 'https://dl.bintray.com/terrakok/terramaven/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}